### ISSUE TITLE
.deb file not install

### ISSUE THREAD

**Issue by Stardust9514** [oja/amazon-music-linux#1]
Hi, the deb file not install, a problem with architecture present.

sudo dpkg -i amazon-music-linux_0.1.0_x86_64.deb

dpkg: attenzione: analisi del file "/var/lib/dpkg/tmp.ci/control" vicino alla riga 5 pacchetto "amazon-music-linux:x86_64":
 "x86_64" non è un nome di architettura valido: carattere "_" non consentito (solo lettere, numeri e caratteri "-")
dpkg: errore nell'elaborare l'archivio amazon-music-linux_0.1.0_x86_64.deb (--install):
 l'architettura del pacchetto (x86_64) non corrisponde a quella del sistema (amd64)
Si sono verificati degli errori nell'elaborazione:
 amazon-music-linux_0.1.0_x86_64.deb

I think you have wrote x86_64 in control file instead amd64

**Comment by clarosj** [comment]
Hi,

For Ubuntu/Debian compile the application as shown here:

electron-installer-debian --src release-builds/amazon-music-linux-linux-x64/ --arch amd64 --config build-config.json

Jose C.

**Comment by oja** [comment]
@Stardust9514 fixed thanks to @clarosj.

**Comment by oja** [comment]
@clarosj @Stardust9514 [linked is the corrected release with the new .deb package](https://github.com/oja/amazon-music-linux/releases/tag/v0.1.1). Please let me know if it works. (I'm not currently using a debian-based distro and temporarily don't have access to a VM for other reasons.)
