### ISSUE TITLE
Close to Tray Option?

### ISSUE THREAD

**Issue by ajithrn** [oja/amazon-music-linux#11]
This is not an issue, a feature request, currently the app exit when close it, can we add an option to close the app to tray?

**Comment by flokol120** [comment]
@ajithrn fixed with latest commit. The application is now minimizing to the tray. I also added a quit option in the tray menu.

**Comment by ajithrn** [comment]
@flokol120 great!

**Comment by ajithrn** [comment]
@flokol120 minimize to tray works great. but there is no option to bring back the minimized app to front. can we make it like when click on the tray icon it will show the app? or add more option in the tray menu?
