### ISSUE TITLE
JS error while starting the app.

### ISSUE THREAD

**Issue by ajithrn** [oja/amazon-music-linux#19]
There is some js error popping up while open the app, it will go away once i click OK and the app works fine without any issues too. 

![js_error](https://user-images.githubusercontent.com/4249484/47379882-c2f83200-d719-11e8-99f0-3ae23e4895ea.png)

OS: elemetary OS Juno (based on ubuntu 18.04)

**Comment by flokol120** [comment]
@ajithrn is the port 3000 blocked by something else on your PC?

**Comment by flokol120** [comment]
Please report whether the commit above fixed your issue.

**Comment by flokol120** [comment]
Closed due to inactivity.
