### ISSUE TITLE
Amazon India Support?

### ISSUE THREAD

**Issue by ajithrn** [oja/amazon-music-linux#9]
This app only works in amazon.com not working on amazon.in can you make a branch for the Indian versions too ?

**Comment by ajithrn** [comment]
sorry for the open request, now its working fine.

**Comment by flokol120** [comment]
@ajithrn Your request is valid! The Indian version is not present. I will create a pull request for you.

**Comment by flokol120** [comment]
fixed with #10.

**Comment by flokol120** [comment]
@ajithrn Your issue should be fixed in the newest release v1.1.0.
